name: Hello World Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 1
        run: echo "Hello World 1"

  say-hello-2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World 2
        run: echo "Hello World 2"
